# Generated by Django 5.0.4 on 2024-06-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_user_email_status'),
        ('account', '0003_user'),
    ]

    operations = [
    ]
