version: "3.8"

services:
  app:
    env_file:
      - .env
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    image: daniyalaamir110/app.expenso:django
    container_name: app.expenso
    command: python expenso/manage.py runserver 0.0.0.0:8000
    depends_on:
      - db
      - rabbit-mq

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    container_name: db.expenso
    environment:
      POSTGRES_USER: expenso
      POSTGRES_PASSWORD: expenso
      POSTGRES_DB: expenso

  rabbit-mq:
    ports:
      - "5672:5672"
    image: rabbitmq:3-management
    container_name: rmq.expenso

  celery:
    env_file:
      - .env
    build: .
    volumes:
      - ./expenso:/app/expenso
    image: daniyalaamir110/celery.expenso:celery
    container_name: celery.expenso
    command: sh -c "cd expenso && celery -A expenso.celery_app worker --loglevel=DEBUG --pool=solo"
    depends_on:
      - app
      - rabbit-mq
